[client]
toolbarMode = "minimal"

[theme]
base = "dark"
primaryColor = "#66fcf1"
backgroundColor = "#0b0c10"
secondaryBackgroundColor = "#222324"
textColor = "#c5c6c7"
font = "monospace"

[server]
enableStaticServing = true